name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv ruff mypy  # jawnie instalujemy ruff i mypy
        uv sync

    - name: Run Ruff (lint)
      run: ruff check issues

    - name: Run Mypy (typy)
      run: mypy issues

    - name: Run tests
      run: pytest
